/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "error":                  "#ba1a1a",
        "surface-container-high": "#ebe8e0",
        "on-primary":             "#ffffff",
        "on-primary-fixed-variant":"#005320",
        "primary-fixed-dim":      "#62df7d",
        "surface-container-low":  "#f6f3eb",
        "surface-container-highest":"#e5e2da",
        "on-surface":             "#1c1c17",
        "on-secondary":           "#ffffff",
        "surface-bright":         "#fcf9f1",
        "on-primary-container":   "#f7fff2",
        "surface-tint":           "#006e2d",
        "inverse-surface":        "#31312b",
        "secondary":              "#3b6842",
        "surface-variant":        "#e5e2da",
        "on-background":          "#1c1c17",
        "primary":                "#006b2c",
        "on-surface-variant":     "#3e4a3d",
        "outline-variant":        "#bdcaba",
        "secondary-container":    "#baecbc",
        "on-tertiary":            "#ffffff",
        "outline":                "#6e7b6c",
        "inverse-primary":        "#62df7d",
        "primary-container":      "#00873a",
        "surface-container-lowest":"#ffffff",
        "surface-dim":            "#dcdad2",
        "surface":                "#fcf9f1",
        "primary-fixed":          "#7ffc97",
        "inverse-on-surface":     "#f3f1e9",
        "surface-container":      "#f1eee6",
        "background":             "#fcf9f1",
      },
      fontFamily: {
        headline: ["Newsreader", "serif"],
        body:     ["Public Sans", "sans-serif"],
        label:    ["Space Grotesk", "monospace"],
      },
      borderRadius: {
        DEFAULT: "0px",
        lg:      "0px",
        xl:      "0px",
        full:    "9999px",
      },
    },
  },
  plugins: [],
}